=== piyongze/exceltool/testtool/src/com/pyz/testtool/xml/testtool.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.pyz.com" 
xmlns="http://www.pyz.com" 
elementFormDefault="qualified">
<xs:element name="tool">
	<xs:complexType>
		<xs:all>
			<xs:element name="document" maxOccurs="5">
				<xs:complexType>
					<xs:all>
						<xs:element name="table" type="xs:string" maxOccurs="1"/>
						<xs:element name="columns" maxOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="column" maxOccurs="10">
										<xs:complexType>
											<xs:all>
												<xs:element name="pos" type="xs:int" maxOccurs="1"/>
												<xs:element name="field" type="xs:string" maxOccurs="1"/>
											</xs:all>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="cache">
				<xs:complexType>
					<xs:all>
						<xs:element name="count" type="xs:int"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="database">
				<xs:complexType>
					<xs:all>
						<xs:element name="dbname" type="xs:string"/>
						<xs:element name="username" type="xs:string"/>
						<xs:element name="password" type="xs:string"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>
</xs:element>
</xs:schema>

=== piyongze/exceltool/testtool/src/com/pyz/testtool/xml/testtool.xml
<?xml version="1.0" encoding="UTF-8"?>
<tool xmlns="http://www.pyz.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.pyz.com testtool.xsd"
>
	<database>
		<dbname>testtool</dbname>
		<username>root</username>
		<password>root</password>
	</database>
	<document>
		<table>com.pyz.testtool.entity.Student</table>
		<columns>
			<column>
				<pos>0</pos>
				<field>id</field>
			</column>
			<column>
				<pos>1</pos>
				<field>name</field>
			</column>
			<column>
				<pos>2</pos>
				<field>sex</field>
			</column>	
		</columns>
	</document>
	<cache>
		<count>5</count>
	</cache>
</tool>
